import AppKit

/*
 Shares plain text between the Mac's pasteboard and the laptop's clipboard. The clipboard follows
 the user: when LaptopScreen comes to the front, a text copied on the Mac in the meantime goes to
 the laptop; a text copied on the laptop lands on the Mac's pasteboard while LaptopScreen is in
 front (or was until a moment ago, when the copy raced the switch to another app). "FOCUS 1|0"
 tells the laptop when to send at all, so its clipboard stays there while the user works elsewhere.
 Entries that password managers mark as concealed or transient (nspasteboard.org) are never sent.
 Lines in both directions: "CLIP+ <base64>" for leading chunks, "CLIP <base64>" for the last one.
 */
final class ClipboardSync {
    /* the laptop announced "CLIPBOARD on"; it can switch sharing off for both directions */
    var isEnabled = false
    var send: ((String) -> Void)?

    private static let chunkBytes = 32 * 1024
    private static let privateTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]
    private let pasteboard = NSPasteboard.general
    /* pasteboard state the laptop already has (sent there or received from there) */
    private var handledChangeCount = -1
    private var resignedAt = Date.distantPast

    /* LaptopScreen came to the front: the laptop may share its clipboard now, and a text copied on the Mac goes over */
    func becameActive() {
        guard isEnabled else { return }
        send?("FOCUS 1")
        guard pasteboard.changeCount != handledChangeCount else { return }
        handledChangeCount = pasteboard.changeCount
        let types = pasteboard.types ?? []
        guard !types.contains(where: { ClipboardSync.privateTypes.contains($0) }),
              let text = pasteboard.string(forType: .string), !text.isEmpty else { return }
        let data = Data(text.utf8)
        guard data.count <= Config.maxClipboardBytes else { return }
        var offset = 0
        while offset < data.count {
            let end = min(offset + ClipboardSync.chunkBytes, data.count)
            let chunk = data.subdata(in: offset..<end).base64EncodedString()
            send?((end < data.count ? "CLIP+ " : "CLIP ") + chunk)
            offset = end
        }
    }

    func resignedActive() {
        resignedAt = Date()
        if isEnabled { send?("FOCUS 0") }
    }

    /* Text from the laptop: taken while LaptopScreen is in front or was until a few seconds ago */
    func received(_ text: String) {
        guard isEnabled, NSApp.isActive || Date().timeIntervalSince(resignedAt) < 3 else { return }
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        handledChangeCount = pasteboard.changeCount
    }
}
